# Reference: https://hub.docker.com/_/postgres/
version: "3"
services:
  db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
volumes:
  pg-data:
