# References:
#   https://hub.docker.com/_/postgres
#   https://dev.to/andre347/how-to-easily-create-a-postgres-database-in-docker-4moj
FROM postgres:15
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB test
#COPY world.sql /docker-entrypoint-initdb.d/